use super::{time::NativeTime, Time};

#[inline(always)]
pub fn get_time() -> Box<dyn Time> {
    // Native environment: using SystemTime to get current time
    return Box::new(NativeTime::new());
}
#[inline(always)]
pub fn sample_fps<T: Time>(since: &T) -> (NativeTime, u64) {
    let deltatime = since.get_elapsed_time();
    (NativeTime::new(), deltatime)
}
#[inline(always)]
pub fn sleep(time: u64) {
    std::thread::sleep(std::time::Duration::from_millis(time));
}

#[inline(always)]
pub fn log<T: std::fmt::Debug>(t: T) {
    println!("{:#?}", t);
}

pub struct KeyManager {
    // Letters
    a: bool,
    b: bool,
    c: bool,
    d: bool,
    e: bool,
    f: bool,
    g: bool,
    h: bool,
    i: bool,
    j: bool,
    k: bool,
    l: bool,
    m: bool,
    n: bool,
    o: bool,
    p: bool,
    q: bool,
    r: bool,
    s: bool,
    t: bool,
    u: bool,
    v: bool,
    w: bool,
    x: bool,
    y: bool,
    z: bool,

    // Numbers
    num0: bool,
    num1: bool,
    num2: bool,
    num3: bool,
    num4: bool,
    num5: bool,
    num6: bool,
    num7: bool,
    num8: bool,
    num9: bool,
    key_pad0: bool,
    key_pad1: bool,
    key_pad2: bool,
    key_pad3: bool,
    key_pad4: bool,
    key_pad5: bool,
    key_pad6: bool,
    key_pad7: bool,
    key_pad8: bool,
    key_pad9: bool,

    // Function Keys
    f1: bool,
    f2: bool,
    f3: bool,
    f4: bool,
    f5: bool,
    f6: bool,
    f7: bool,
    f8: bool,
    f9: bool,
    f10: bool,
    f11: bool,
    f12: bool,
    f13: bool,
    f14: bool,
    f15: bool,
    f16: bool,
    f17: bool,
    f18: bool,
    f19: bool,
    f20: bool,
    f21: bool,
    f22: bool,
    f23: bool,
    f24: bool,

    // Modifiers
    left_shift: bool,
    right_shift: bool,
    left_control: bool,
    right_control: bool,
    left_alt: bool,
    right_alt: bool,
    left_super: bool,
    right_super: bool,

    // Symbols / Punctuation
    space: bool,
    enter: bool,
    escape: bool,
    backspace: bool,
    tab: bool,
    comma: bool,
    period: bool,
    minus: bool,
    equal: bool,
    left_bracket: bool,
    right_bracket: bool,
    backslash: bool,
    semicolon: bool,
    quote: bool,
    tilde: bool,
    slash: bool,
    grave: bool,

    // Arrow keys
    up: bool,
    down: bool,
    left: bool,
    right: bool,

    // Editing keys
    insert: bool,
    delete: bool,
    home: bool,
    end: bool,
    page_up: bool,
    page_down: bool,

    // Lock keys
    caps_lock: bool,
    num_lock: bool,
    scroll_lock: bool,

    // Keypad operations
    key_pad_divide: bool,
    key_pad_multiply: bool,
    key_pad_subtract: bool,
    key_pad_add: bool,
    key_pad_decimal: bool,
    key_pad_enter: bool,

    // International & special characters
    ä: bool,
    ü: bool,
    ö: bool,
    ss: bool,
    â: bool,
    ú: bool,
    ô: bool,
    î: bool,
    ê: bool,
    ð: bool,
    œ: bool,
    á: bool,
    ý: bool,
    ï: bool,
    ñ: bool,
    ò: bool,
    é: bool,
    å: bool,
    æ: bool,
    ø: bool,
    í: bool,
    þ: bool,
    ù: bool,
    ì: bool,

    // Multimedia keys
    media_play_pause: bool,
    media_stop: bool,
    media_next: bool,
    media_prev: bool,
    volume_up: bool,
    volume_down: bool,
    mute: bool,

    // Browser/OS keys
    browser_back: bool,
    browser_forward: bool,
    browser_refresh: bool,
    browser_home: bool,
    launch_mail: bool,
    launch_app1: bool,
    launch_app2: bool,

    // Platform-specific
    menu: bool,
    print_screen: bool,
    pause: bool,
    application: bool,

    apostrophe: bool,
    f25: bool,

    key_pad_equal: bool,
    world_1: bool,
    world_2: bool,
}

impl KeyManager {
    pub fn new() -> Self {
        KeyManager {
            a: false,
            b: false,
            c: false,
            d: false,
            e: false,
            f: false,
            g: false,
            h: false,
            i: false,
            j: false,
            k: false,
            l: false,
            m: false,
            n: false,
            o: false,
            p: false,
            q: false,
            r: false,
            s: false,
            t: false,
            u: false,
            v: false,
            w: false,
            x: false,
            y: false,
            z: false,
            num0: false,
            num1: false,
            num2: false,
            num3: false,
            num4: false,
            num5: false,
            num6: false,
            num7: false,
            num8: false,
            num9: false,
            key_pad0: false,
            key_pad1: false,
            key_pad2: false,
            key_pad3: false,
            key_pad4: false,
            key_pad5: false,
            key_pad6: false,
            key_pad7: false,
            key_pad8: false,
            key_pad9: false,
            f1: false,
            f2: false,
            f3: false,
            f4: false,
            f5: false,
            f6: false,
            f7: false,
            f8: false,
            f9: false,
            f10: false,
            f11: false,
            f12: false,
            f13: false,
            f14: false,
            f15: false,
            f16: false,
            f17: false,
            f18: false,
            f19: false,
            f20: false,
            f21: false,
            f22: false,
            f23: false,
            f24: false,
            left_shift: false,
            right_shift: false,
            left_control: false,
            right_control: false,
            left_alt: false,
            right_alt: false,
            left_super: false,
            right_super: false,
            space: false,
            enter: false,
            escape: false,
            backspace: false,
            tab: false,
            comma: false,
            period: false,
            minus: false,
            equal: false,
            left_bracket: false,
            right_bracket: false,
            backslash: false,
            semicolon: false,
            quote: false,
            tilde: false,
            slash: false,
            grave: false,
            up: false,
            down: false,
            left: false,
            right: false,
            insert: false,
            delete: false,
            home: false,
            end: false,
            page_up: false,
            page_down: false,
            caps_lock: false,
            num_lock: false,
            scroll_lock: false,
            key_pad_divide: false,
            key_pad_multiply: false,
            key_pad_subtract: false,
            key_pad_add: false,
            key_pad_decimal: false,
            key_pad_enter: false,
            ä: false,
            ü: false,
            ö: false,
            ss: false,
            â: false,
            ú: false,
            ô: false,
            î: false,
            ê: false,
            ð: false,
            œ: false,
            á: false,
            ý: false,
            ï: false,
            ñ: false,
            ò: false,
            é: false,
            å: false,
            æ: false,
            ø: false,
            í: false,
            þ: false,
            media_play_pause: false,
            media_stop: false,
            media_next: false,
            media_prev: false,
            volume_up: false,
            volume_down: false,
            mute: false,
            browser_back: false,
            browser_forward: false,
            browser_refresh: false,
            browser_home: false,
            launch_mail: false,
            launch_app1: false,
            launch_app2: false,
            menu: false,
            print_screen: false,
            pause: false,
            application: false,
            key_pad_equal: false,
            apostrophe: false,
            f25: false,
            world_1: false,
            world_2: false,
            ì: false,
            ù: false,
        }
    }

    pub fn is_key_pressed(&self, keycode: KeyCode) -> bool {
        map_keycode(keycode, &self)
    }
    pub fn set_key_state(&mut self, keycode: KeyCode, value: bool) {
        set_keycode(keycode, self, value);
    }
}

pub struct MouseManager {
    scroll_x: f64,
    scroll_y: f64,
    left_mouse_button: bool,
    right_mouse_button: bool,
    middle_mouse_button: bool,
    // Other mouse buttons not supported due to me not having a mouse that supports them
}

impl MouseManager {
    pub fn new() -> Self {
        MouseManager {
            scroll_x: 0.0,
            scroll_y: 0.0,
            left_mouse_button: false,
            right_mouse_button: false,
            middle_mouse_button: false,
        }
    }
    pub fn set_scroll(&mut self, x: f64, y: f64) {
        self.scroll_x = x;
        self.scroll_y = y;
    }
    pub fn add_scroll(&mut self, x: f64, y: f64) {
        self.scroll_x += x;
        self.scroll_y += y;
    }
    pub fn reset_scroll(&mut self) {
        self.scroll_x = 0.0;
        self.scroll_y = 0.0;
    }
    pub fn get_scroll(&self) -> (f64, f64) {
        (self.scroll_x, self.scroll_y)
    }
    pub fn is_mouse_button_pressed(&self, button: MouseButton) -> bool {
        map_button(button, &self)
    }
    pub fn set_mouse_button_state(&mut self, button: MouseButton, value: bool) {
        set_mouse_button(button, self, value);
    }
}

use super::{KeyCode, MouseButton};

pub const fn map_button(
    button: MouseButton,
    mousemanager: &MouseManager,
) -> bool {
    match button {
        MouseButton::Left => mousemanager.left_mouse_button,
        MouseButton::Right => mousemanager.right_mouse_button,
        MouseButton::Middle => mousemanager.middle_mouse_button,
        MouseButton::Unsupported => false,
    }
}
pub const fn set_mouse_button(
    button: MouseButton,
    mousemanager: &mut MouseManager,
    value: bool,
) {
    match button {
        MouseButton::Left => mousemanager.left_mouse_button = value,
        MouseButton::Right => mousemanager.right_mouse_button = value,
        MouseButton::Middle => mousemanager.middle_mouse_button = value,
        MouseButton::Unsupported => (),
    }
}

pub const fn map_keycode(keycode: KeyCode, keymanager: &KeyManager) -> bool {
    match keycode {
        KeyCode::A => keymanager.a,
        KeyCode::B => keymanager.b,
        KeyCode::C => keymanager.c,
        KeyCode::D => keymanager.d,
        KeyCode::E => keymanager.e,
        KeyCode::F => keymanager.f,
        KeyCode::G => keymanager.g,
        KeyCode::H => keymanager.h,
        KeyCode::I => keymanager.i,
        KeyCode::J => keymanager.j,
        KeyCode::K => keymanager.k,
        KeyCode::L => keymanager.l,
        KeyCode::M => keymanager.m,
        KeyCode::N => keymanager.n,
        KeyCode::O => keymanager.o,
        KeyCode::P => keymanager.p,
        KeyCode::Q => keymanager.q,
        KeyCode::R => keymanager.r,
        KeyCode::S => keymanager.s,
        KeyCode::T => keymanager.t,
        KeyCode::U => keymanager.u,
        KeyCode::V => keymanager.v,
        KeyCode::W => keymanager.w,
        KeyCode::X => keymanager.x,
        KeyCode::Y => keymanager.y,
        KeyCode::Z => keymanager.z,
        KeyCode::Num0 => keymanager.num0,
        KeyCode::Num1 => keymanager.num1,
        KeyCode::Num2 => keymanager.num2,
        KeyCode::Num3 => keymanager.num3,
        KeyCode::Num4 => keymanager.num4,
        KeyCode::Num5 => keymanager.num5,
        KeyCode::Num6 => keymanager.num6,
        KeyCode::Num7 => keymanager.num7,
        KeyCode::Num8 => keymanager.num8,
        KeyCode::Num9 => keymanager.num9,
        KeyCode::KeyPad0 => keymanager.key_pad0,
        KeyCode::KeyPad1 => keymanager.key_pad1,
        KeyCode::KeyPad2 => keymanager.key_pad2,
        KeyCode::KeyPad3 => keymanager.key_pad3,
        KeyCode::KeyPad4 => keymanager.key_pad4,
        KeyCode::KeyPad5 => keymanager.key_pad5,
        KeyCode::KeyPad6 => keymanager.key_pad6,
        KeyCode::KeyPad7 => keymanager.key_pad7,
        KeyCode::KeyPad8 => keymanager.key_pad8,
        KeyCode::KeyPad9 => keymanager.key_pad9,
        KeyCode::F1 => keymanager.f1,
        KeyCode::F2 => keymanager.f2,
        KeyCode::F3 => keymanager.f3,
        KeyCode::F4 => keymanager.f4,
        KeyCode::F5 => keymanager.f5,
        KeyCode::F6 => keymanager.f6,
        KeyCode::F7 => keymanager.f7,
        KeyCode::F8 => keymanager.f8,
        KeyCode::F9 => keymanager.f9,
        KeyCode::F10 => keymanager.f10,
        KeyCode::F11 => keymanager.f11,
        KeyCode::F12 => keymanager.f12,
        KeyCode::F13 => keymanager.f13,
        KeyCode::F14 => keymanager.f14,
        KeyCode::F15 => keymanager.f15,
        KeyCode::F16 => keymanager.f16,
        KeyCode::F17 => keymanager.f17,
        KeyCode::F18 => keymanager.f18,
        KeyCode::F19 => keymanager.f19,
        KeyCode::F20 => keymanager.f20,
        KeyCode::F21 => keymanager.f21,
        KeyCode::F22 => keymanager.f22,
        KeyCode::F23 => keymanager.f23,
        KeyCode::F24 => keymanager.f24,
        KeyCode::Application => keymanager.application,
        KeyCode::Escape => keymanager.escape,
        KeyCode::Enter => keymanager.enter,
        KeyCode::Backspace => keymanager.backspace,
        KeyCode::Tab => keymanager.tab,
        KeyCode::Space => keymanager.space,
        KeyCode::Minus => keymanager.minus,
        KeyCode::Equal => keymanager.equal,
        KeyCode::LeftBracket => keymanager.left_bracket,
        KeyCode::RightBracket => keymanager.right_bracket,
        KeyCode::Backslash => keymanager.backslash,
        KeyCode::Semicolon => keymanager.semicolon,
        KeyCode::Grave => keymanager.grave,
        KeyCode::Comma => keymanager.comma,
        KeyCode::Period => keymanager.period,
        KeyCode::Slash => keymanager.slash,
        KeyCode::CapsLock => keymanager.caps_lock,
        KeyCode::ScrollLock => keymanager.scroll_lock,
        KeyCode::NumLock => keymanager.num_lock,
        KeyCode::BrowserBack => keymanager.browser_back,
        KeyCode::BrowserForward => keymanager.browser_forward,
        KeyCode::KeyPadAdd => keymanager.key_pad_add,
        KeyCode::KeyPadSubtract => keymanager.key_pad_subtract,
        KeyCode::KeyPadMultiply => keymanager.key_pad_multiply,
        KeyCode::KeyPadDivide => keymanager.key_pad_divide,
        KeyCode::KeyPadEnter => keymanager.key_pad_enter,
        KeyCode::KeyPadDecimal => keymanager.key_pad_decimal,
        KeyCode::LeftShift => keymanager.left_shift,
        KeyCode::LeftControl => keymanager.left_control,
        KeyCode::LeftAlt => keymanager.left_alt,
        KeyCode::LeftSuper => keymanager.left_super,
        KeyCode::RightShift => keymanager.right_shift,
        KeyCode::RightControl => keymanager.right_control,
        KeyCode::RightAlt => keymanager.right_alt,
        KeyCode::RightSuper => keymanager.right_super,
        KeyCode::Menu => keymanager.menu,
        KeyCode::Quote => keymanager.quote,
        KeyCode::Tilde => keymanager.tilde,
        KeyCode::Up => keymanager.up,
        KeyCode::Down => keymanager.down,
        KeyCode::Left => keymanager.left,
        KeyCode::Right => keymanager.right,
        KeyCode::PageUp => keymanager.page_up,
        KeyCode::PageDown => keymanager.page_down,
        KeyCode::Home => keymanager.home,
        KeyCode::End => keymanager.end,
        KeyCode::Insert => keymanager.insert,
        KeyCode::Delete => keymanager.delete,

        KeyCode::Ä => keymanager.ä,

        KeyCode::Ê => keymanager.ê,
        KeyCode::Ô => keymanager.ô,
        KeyCode::Ù => keymanager.ù,
        KeyCode::Å => keymanager.å,
        KeyCode::Æ => keymanager.æ,
        KeyCode::Ø => keymanager.ø,
        KeyCode::Ü => keymanager.ü,
        KeyCode::Ì => keymanager.ì,
        KeyCode::BrowserHome => keymanager.browser_home,
        KeyCode::BrowserRefresh => keymanager.browser_refresh,
        KeyCode::LaunchApp1 => keymanager.launch_app1,
        KeyCode::LaunchApp2 => keymanager.launch_app2,
        KeyCode::LaunchMail => keymanager.launch_mail,
        KeyCode::MediaNext => keymanager.media_next,
        KeyCode::MediaPlayPause => keymanager.media_play_pause,
        KeyCode::MediaPrev => keymanager.media_prev,
        KeyCode::MediaStop => keymanager.media_stop,
        KeyCode::Mute => keymanager.mute,
        KeyCode::PrintScreen => keymanager.print_screen,
        KeyCode::SS => keymanager.ss,
        KeyCode::VolumeDown => keymanager.volume_down,
        KeyCode::VolumeUp => keymanager.volume_up,
        KeyCode::Á => keymanager.á,
        KeyCode::Â => keymanager.â,
        KeyCode::Î => keymanager.î,
        KeyCode::Ï => keymanager.ï,
        KeyCode::Ð => keymanager.ð,
        KeyCode::Ñ => keymanager.ñ,
        KeyCode::Ò => keymanager.ò,
        KeyCode::Ö => keymanager.ö,
        KeyCode::Ú => keymanager.ú,
        KeyCode::Ý => keymanager.ý,
        KeyCode::Þ => keymanager.þ,
        KeyCode::Œ => keymanager.œ,

        KeyCode::Pause => keymanager.pause,
        KeyCode::Apostrophe => keymanager.apostrophe,
        KeyCode::F25 => keymanager.f25,
        KeyCode::KeyPadEqual => keymanager.key_pad_equal,
        KeyCode::World1 => keymanager.world_1,
        KeyCode::World2 => keymanager.world_2,

        KeyCode::Unknown => false,
    }
}

pub fn set_keycode(keycode: KeyCode, keymanager: &mut KeyManager, value: bool) {
    match keycode {
        KeyCode::A => keymanager.a = value,
        KeyCode::B => keymanager.b = value,
        KeyCode::C => keymanager.c = value,
        KeyCode::D => keymanager.d = value,
        KeyCode::E => keymanager.e = value,
        KeyCode::F => keymanager.f = value,
        KeyCode::G => keymanager.g = value,
        KeyCode::H => keymanager.h = value,
        KeyCode::I => keymanager.i = value,
        KeyCode::J => keymanager.j = value,
        KeyCode::K => keymanager.k = value,
        KeyCode::L => keymanager.l = value,
        KeyCode::M => keymanager.m = value,
        KeyCode::N => keymanager.n = value,
        KeyCode::O => keymanager.o = value,
        KeyCode::P => keymanager.p = value,
        KeyCode::Q => keymanager.q = value,
        KeyCode::R => keymanager.r = value,
        KeyCode::S => keymanager.s = value,
        KeyCode::T => keymanager.t = value,
        KeyCode::U => keymanager.u = value,
        KeyCode::V => keymanager.v = value,
        KeyCode::W => keymanager.w = value,
        KeyCode::X => keymanager.x = value,
        KeyCode::Y => keymanager.y = value,
        KeyCode::Z => keymanager.z = value,
        KeyCode::Num0 => keymanager.num0 = value,
        KeyCode::Num1 => keymanager.num1 = value,
        KeyCode::Num2 => keymanager.num2 = value,
        KeyCode::Num3 => keymanager.num3 = value,
        KeyCode::Num4 => keymanager.num4 = value,
        KeyCode::Num5 => keymanager.num5 = value,
        KeyCode::Num6 => keymanager.num6 = value,
        KeyCode::Num7 => keymanager.num7 = value,
        KeyCode::Num8 => keymanager.num8 = value,
        KeyCode::Num9 => keymanager.num9 = value,
        KeyCode::KeyPad0 => keymanager.key_pad0 = value,
        KeyCode::KeyPad1 => keymanager.key_pad1 = value,
        KeyCode::KeyPad2 => keymanager.key_pad2 = value,
        KeyCode::KeyPad3 => keymanager.key_pad3 = value,
        KeyCode::KeyPad4 => keymanager.key_pad4 = value,
        KeyCode::KeyPad5 => keymanager.key_pad5 = value,
        KeyCode::KeyPad6 => keymanager.key_pad6 = value,
        KeyCode::KeyPad7 => keymanager.key_pad7 = value,
        KeyCode::KeyPad8 => keymanager.key_pad8 = value,
        KeyCode::KeyPad9 => keymanager.key_pad9 = value,
        KeyCode::F1 => keymanager.f1 = value,
        KeyCode::F2 => keymanager.f2 = value,
        KeyCode::F3 => keymanager.f3 = value,
        KeyCode::F4 => keymanager.f4 = value,
        KeyCode::F5 => keymanager.f5 = value,
        KeyCode::F6 => keymanager.f6 = value,
        KeyCode::F7 => keymanager.f7 = value,
        KeyCode::F8 => keymanager.f8 = value,
        KeyCode::F9 => keymanager.f9 = value,
        KeyCode::F10 => keymanager.f10 = value,
        KeyCode::F11 => keymanager.f11 = value,
        KeyCode::F12 => keymanager.f12 = value,
        KeyCode::F13 => keymanager.f13 = value,
        KeyCode::F14 => keymanager.f14 = value,
        KeyCode::F15 => keymanager.f15 = value,
        KeyCode::F16 => keymanager.f16 = value,
        KeyCode::F17 => keymanager.f17 = value,
        KeyCode::F18 => keymanager.f18 = value,
        KeyCode::F19 => keymanager.f19 = value,
        KeyCode::F20 => keymanager.f20 = value,
        KeyCode::F21 => keymanager.f21 = value,
        KeyCode::F22 => keymanager.f22 = value,
        KeyCode::F23 => keymanager.f23 = value,
        KeyCode::F24 => keymanager.f24 = value,
        KeyCode::Application => keymanager.application = value,
        KeyCode::Escape => keymanager.escape = value,
        KeyCode::Enter => keymanager.enter = value,
        KeyCode::Backspace => keymanager.backspace = value,
        KeyCode::Tab => keymanager.tab = value,
        KeyCode::Space => keymanager.space = value,
        KeyCode::Minus => keymanager.minus = value,
        KeyCode::Equal => keymanager.equal = value,
        KeyCode::LeftBracket => keymanager.left_bracket = value,
        KeyCode::RightBracket => keymanager.right_bracket = value,
        KeyCode::Backslash => keymanager.backslash = value,
        KeyCode::Semicolon => keymanager.semicolon = value,
        KeyCode::Grave => keymanager.grave = value,
        KeyCode::Comma => keymanager.comma = value,
        KeyCode::Period => keymanager.period = value,
        KeyCode::Slash => keymanager.slash = value,
        KeyCode::CapsLock => keymanager.caps_lock = value,
        KeyCode::ScrollLock => keymanager.scroll_lock = value,
        KeyCode::NumLock => keymanager.num_lock = value,
        KeyCode::BrowserBack => keymanager.browser_back = value,
        KeyCode::BrowserForward => keymanager.browser_forward = value,
        KeyCode::KeyPadAdd => keymanager.key_pad_add = value,
        KeyCode::KeyPadSubtract => keymanager.key_pad_subtract = value,
        KeyCode::KeyPadMultiply => keymanager.key_pad_multiply = value,
        KeyCode::KeyPadDivide => keymanager.key_pad_divide = value,
        KeyCode::KeyPadEnter => keymanager.key_pad_enter = value,
        KeyCode::KeyPadDecimal => keymanager.key_pad_decimal = value,
        KeyCode::LeftShift => keymanager.left_shift = value,
        KeyCode::LeftControl => keymanager.left_control = value,
        KeyCode::LeftAlt => keymanager.left_alt = value,
        KeyCode::LeftSuper => keymanager.left_super = value,
        KeyCode::RightShift => keymanager.right_shift = value,
        KeyCode::RightControl => keymanager.right_control = value,
        KeyCode::RightAlt => keymanager.right_alt = value,
        KeyCode::RightSuper => keymanager.right_super = value,
        KeyCode::Menu => keymanager.menu = value,
        KeyCode::Quote => keymanager.quote = value,
        KeyCode::Tilde => keymanager.tilde = value,
        KeyCode::Up => keymanager.up = value,
        KeyCode::Down => keymanager.down = value,
        KeyCode::Left => keymanager.left = value,
        KeyCode::Right => keymanager.right = value,
        KeyCode::PageUp => keymanager.page_up = value,
        KeyCode::PageDown => keymanager.page_down = value,
        KeyCode::Home => keymanager.home = value,
        KeyCode::End => keymanager.end = value,
        KeyCode::Insert => keymanager.insert = value,
        KeyCode::Delete => keymanager.delete = value,
        KeyCode::Ä => keymanager.ä = value,
        KeyCode::Ê => keymanager.ê = value,
        KeyCode::Ô => keymanager.ô = value,
        KeyCode::Ù => keymanager.ù = value,
        KeyCode::Å => keymanager.å = value,
        KeyCode::Æ => keymanager.æ = value,
        KeyCode::Ø => keymanager.ø = value,
        KeyCode::Ü => keymanager.ü = value,
        KeyCode::Ì => keymanager.ì = value,
        KeyCode::BrowserHome => keymanager.browser_home = value,
        KeyCode::BrowserRefresh => keymanager.browser_refresh = value,
        KeyCode::LaunchApp1 => keymanager.launch_app1 = value,
        KeyCode::LaunchApp2 => keymanager.launch_app2 = value,
        KeyCode::LaunchMail => keymanager.launch_mail = value,
        KeyCode::MediaNext => keymanager.media_next = value,
        KeyCode::MediaPlayPause => keymanager.media_play_pause = value,
        KeyCode::MediaPrev => keymanager.media_prev = value,
        KeyCode::MediaStop => keymanager.media_stop = value,
        KeyCode::Mute => keymanager.mute = value,
        KeyCode::PrintScreen => keymanager.print_screen = value,
        KeyCode::SS => keymanager.ss = value,
        KeyCode::VolumeDown => keymanager.volume_down = value,
        KeyCode::VolumeUp => keymanager.volume_up = value,
        KeyCode::Á => keymanager.á = value,
        KeyCode::Â => keymanager.â = value,
        KeyCode::Î => keymanager.î = value,
        KeyCode::Ï => keymanager.ï = value,
        KeyCode::Ð => keymanager.ð = value,
        KeyCode::Ñ => keymanager.ñ = value,
        KeyCode::Ò => keymanager.ò = value,
        KeyCode::Ö => keymanager.ö = value,
        KeyCode::Ú => keymanager.ú = value,
        KeyCode::Ý => keymanager.ý = value,
        KeyCode::Þ => keymanager.þ = value,
        KeyCode::Œ => keymanager.œ = value,
        KeyCode::Pause => keymanager.pause = value,
        KeyCode::Apostrophe => keymanager.apostrophe = value,
        KeyCode::F25 => keymanager.f25 = value,
        KeyCode::KeyPadEqual => keymanager.key_pad_equal = value,
        KeyCode::World1 => keymanager.world_1 = value,
        KeyCode::World2 => keymanager.world_2 = value,
        KeyCode::Unknown => (),
    }
}

#[cfg(target_os = "windows")]
mod windows;
pub use windows::*;
